

import Header from "@/components/layout/Header";
import "./globals.css";
import { poppins } from "@/components/ui/fonts";
import Footer from "@/components/layout/Footer";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";


export const metadata = {
  
  title: "VELUSY",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased h-screen flex flex-col`}
      >
        <Header></Header>
        <main className="flex-grow flex items-center justify-center">
          <ErrorBoundary FallbackComponent={Error}>
            {children}
          </ErrorBoundary>
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
