

import Header from "@/components/layout/Header";
import "./globals.css";
import { poppins } from "@/components/ui/fonts";
import Footer from "@/components/layout/Footer";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import Script from "next/script";


export const metadata = {

  title: "VELUSY",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html lang="en">
      {/* <Script src="/assets/lang-config.js" strategy="beforeInteractive" />
      <Script src="/assets/translation.js" strategy="beforeInteractive" />
      <Script src="//translate.google.com/translate_a/element.js?cb=TranslateInit" strategy="afterInteractive" /> */}

      <body
        className={`${poppins.className} antialiased h-screen flex flex-col`}
      >
        <div id="google_translate_element" style={{ display: 'none' }}></div>

        <Header></Header>
        <main className="flex-grow flex items-center justify-center">
          <ErrorBoundary FallbackComponent={Error}>
            {children}
          </ErrorBoundary>
        </main>
        <Footer></Footer>

        <Script
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />
        <Script id="google-translate-init" strategy="afterInteractive">
          {`
            function googleTranslateElementInit() {
              new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
            }
          `}
        </Script>
      </body>
    </html>
  );
}
